// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_uGO7XBg6nF14crZi7F-By5_AZIQzsFo',
    appId: '1:470651353684:web:5158ca6bba91b8f98ecbc1',
    messagingSenderId: '470651353684',
    projectId: 'padelapp-f3df2',
    authDomain: 'padelapp-f3df2.firebaseapp.com',
    storageBucket: 'padelapp-f3df2.appspot.com',
    measurementId: 'G-1NKCQG1QNL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCz7Zelaxz3ggHKLDJ5Z5xwlS8Y8zRAKs',
    appId: '1:470651353684:android:9e3619e0cb8f4d768ecbc1',
    messagingSenderId: '470651353684',
    projectId: 'padelapp-f3df2',
    storageBucket: 'padelapp-f3df2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwRn2AZHaI-wtYRgshdobMgVnNjos7tiI',
    appId: '1:470651353684:ios:60bab5a08376a5c98ecbc1',
    messagingSenderId: '470651353684',
    projectId: 'padelapp-f3df2',
    storageBucket: 'padelapp-f3df2.appspot.com',
    iosBundleId: 'com.example.introMobileProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwRn2AZHaI-wtYRgshdobMgVnNjos7tiI',
    appId: '1:470651353684:ios:ae39f42b034e5c358ecbc1',
    messagingSenderId: '470651353684',
    projectId: 'padelapp-f3df2',
    storageBucket: 'padelapp-f3df2.appspot.com',
    iosBundleId: 'com.example.introMobileProject.RunnerTests',
  );
}
